### ISSUE TITLE
rotate while dead

### ISSUE THREAD

**Issue by chrinilo** [Hiroshji/PyQT6-Tetris#4]
you can rotate the tetrimenos with space and arrow keys after you should be dead

**Comment by Hiroshji** [comment]
the issue got resolved in v1.3 after fixing the duplication glitch.
turns out it kept moving becuase the lines werent cleared correctly.

heres the link to see how the issue got resolved.
https://github.com/Hiroshji/PyQT6-Tetris/issues/5
